### ISSUE TITLE
Remove `typeof 'string'` check for secret

### ISSUE THREAD

**Issue by jeffijoe** [feathersjs/feathers-authentication-jwt#9]
A secret can also be a buffer (when passed to `jsonwebtoken`) and the string check will prevent that.

Offending line: https://github.com/feathersjs/feathers-authentication-jwt/blob/master/src/index.js#L43

**Comment by daffl** [comment]
Did you try if it works removing this line of code from the code for this package in `node_modules`?

**Comment by jeffijoe** [comment]
Yes, it works with that line removed.
